### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-temp-dash#3]
# 🙏🏽

**Comment by eliasmalik** [comment]
<img height="600px" alt="screenshot_20181113-174637" src="https://user-images.githubusercontent.com/12719553/48432469-51d1fa80-e76c-11e8-8379-bf60c36f6062.png" />

Mobile view could do with a bit of work (used for forgotten passwords on the native app)

**Comment by astroash** [comment]
This is designed desktop ~~first~~ only. There’s no need for TWINE_ADMIN to use this on handheld devices.

**Comment by eliasmalik** [comment]
The native apps "forgot password" link goes to this page.

**Comment by astroash** [comment]
🙈

**Comment by edwardwptc** [comment]
The Volunteer data download only includes user ID and not name. Was this intentional? 

Note that visitor data doesn't include name either, only Used ID, and I don't have a problem with that I think. 

CB's are more likely to want to identify volunteers by name because A: They need to track their volunteers and B: The Admin smartphone app shows logs by name, so it's not intuitive that this doesn't.

Visitors names are less critical because that's more about raw headcount than knowing that Barry forgot to go to Judo last thursday etc.

**Comment by edwardwptc** [comment]
Also can't see where to generate new Admin Code?

**Comment by edwardwptc** [comment]
All other usability looks good - lack of search function isn't a problem because all values are displayed on one page and ctrl-f works fine. Thank you for your patience in me getting to this.

**Comment by astroash** [comment]
@edwardwptc thank you for your feedback!

> The Volunteer data download only includes user ID and not name. Was this intentional?

I copied this functionality from the visitor app. Do you want me to add in users names? 

> Also can't see where to generate new Admin Code?

Admin Codes are now generated on the server when a new community business is created. This is one less task for you to do manually 🙂

**Comment by edwardwptc** [comment]
Hi @astroash  

Yes please, users names for volunteers in the outputs. 

Cool @ the admin code thing. Only thing to mention is that once or twice (literally once or twice) I've had to delete the existing admin code and regenerate it during a session as it wasn't working. It may have been that it wasn't particularly clear what was an O or an 0 or an l or an I (L and i) and having to guess repeatedly would be unprofessional. So I'd just quickly regenerate it to avoid such hassles.

So I can't say 100% if it was that on those occasions the codes were genuinely not working and needed to be regenerated, or if it was just input errors as it's hard to identify the letters. 

What I can do in future is simply copy the text to word and change the font to something that clearly shows the difference in the letters. If it still doesn't work it'll be clear that sometimes they just don't work and need to be recreated, though I don't imagine that to be the case really. I think the other explanation is far more likely.
